name: TestPlugin
version: 1.0
author: wyatt_01
main: me.wyatt.BPick.Main
description: Bountiful Pickaxe Plugin!

commands:
  test:
    aliases: [testing]
    description: This is a test plugin.
  chatplayer:
    aliases: [chatforplayer]
    description: Chats on another players behalf.
